# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'Example' do
pod 'pop', '~> 1.0.8'
pod 'SnapKit', '~> 0.16.0'
end

target 'ExampleTests' do

end

